import org.skyscreamer.jsonassert.JSONCompare;
import org.skyscreamer.jsonassert.JSONCompareConfig;
import org.skyscreamer.jsonassert.JSONCompareMode;
import org.skyscreamer.jsonassert.JSONCompareResult;
import org.skyscreamer.jsonassert.comparator.ComplexComparator;
import org.skyscreamer.jsonassert.comparator.JSONComparator;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

/**
 * <br>
 *
 * @author zippoy
 * @date 2019-10-09
 */
public class JSONDiffTest {

    public static void main(String[] args) throws IOException {
        String expected = "{\"ret\":true,\"isInland\":0,\"q\":\"香港fdafafasfdsafdsafas\",\"data\":[{\"suggestType\":\"district\",\"ahead\":\"荃湾\",\"isSupplement\":0,\"recallName\":\"荃湾\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"city\"},{\"suggestType\":\"university\",\"ahead\":\"香港大学\",\"isSupplement\":0,\"recallName\":\"香港大学\",\"recommends\":[],\"showEName\":\"Hong Kong University\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港海洋公园\",\"isSupplement\":0,\"recallName\":\"香港海洋公园\",\"recommends\":[],\"showEName\":\"HongKong Ocean Park\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港体育馆\",\"isSupplement\":0,\"recallName\":\"香港体育馆\",\"recommends\":[\"aaa\",\"bbb\",\"ccc\"],\"showEName\":\"Hong Kong Coliseum (Coliseum)\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港会议展览中心\",\"isSupplement\":0,\"recallName\":\"香港会议展览中心\",\"recommends\":[],\"showEName\":\"Hong Kong Convention and Exhibition Centre\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港中文大学\",\"isSupplement\":0,\"recallName\":\"香港中文大学\",\"recommends\":[],\"showEName\":\"The Chinese University of Hong Kong\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港理工大学\",\"isSupplement\":0,\"recallName\":\"香港理工大学\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"poi\"}],\"city\":\"香港\",\"crossCity\":[]}";
        String actual = "{\"ret\":true,\"isInland\":0,\"q\":\"香港fdafafasfdsafdsafas\",\"data\":[{\"suggestType\":\"district\",\"ahead\":\"荃湾\",\"isSupplement\":0,\"recallName\":\"荃湾\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"city\"},{\"suggestType\":\"university\",\"ahead\":\"香港大学\",\"isSupplement\":0,\"recallName\":\"香港大学\",\"recommends\":[],\"showEName\":\"Hong Kong University\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港海洋公园\",\"isSupplement\":0,\"recallName\":\"香港海洋公园\",\"recommends\":[],\"showEName\":\"HongKong Ocean Park\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港体育馆\",\"isSupplement\":0,\"recallName\":\"香港体育馆\",\"recommends\":[\"bbb\",\"ccc\",\"aaa\"],\"showEName\":\"Hong Kong Coliseum (Coliseum)\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港会议展览中心\",\"isSupplement\":0,\"recallName\":\"香港会议展览中心\",\"recommends\":[],\"showEName\":\"Hong Kong Convention and Exhibition Centre\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港中文大学\",\"isSupplement\":0,\"recallName\":\"香港中文大学\",\"recommends\":[],\"showEName\":\"The Chinese University of Hong Kong\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港理工大学\",\"isSupplement\":0,\"recallName\":\"香港理工大学\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"poi\"}],\"city\":\"香港\",\"crossCity\":[]}";
        //String actual = "{\"ret\":true,\"isInland\":0,\"q\":\"香港fdafafasfdsafdsafas\",\"data\":[{\"suggestType\":\"scenic\",\"ahead\":\"香港会议展览中心\",\"isSupplement\":0,\"recallName\":\"香港会议展览中心\",\"recommends\":[],\"showEName\":\"Hong Kong Convention and Exhibition Centre\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港中文大学\",\"isSupplement\":0,\"recallName\":\"香港中文大学\",\"recommends\":[],\"showEName\":\"The Chinese University of Hong Kong\",\"parentType\":\"poi\"},{\"suggestType\":\"district\",\"ahead\":\"荃湾\",\"isSupplement\":0,\"recallName\":\"荃湾\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"city\"},{\"suggestType\":\"university\",\"ahead\":\"香港大学\",\"isSupplement\":0,\"recallName\":\"香港大学\",\"recommends\":[],\"showEName\":\"Hong Kong University\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港海洋公园\",\"isSupplement\":0,\"recallName\":\"香港海洋公园\",\"recommends\":[],\"showEName\":\"HongKong Ocean Park\",\"parentType\":\"poi\"},{\"suggestType\":\"scenic\",\"ahead\":\"香港体育馆\",\"isSupplement\":0,\"recallName\":\"香港体育馆\",\"recommends\":[\"ccc\",\"aaa\",\"bbb\"],\"showEName\":\"Hong Kong Coliseum (Coliseum)\",\"parentType\":\"poi\"},{\"suggestType\":\"university\",\"ahead\":\"香港理工大学\",\"isSupplement\":0,\"recallName\":\"香港理工大学\",\"recommends\":[],\"showEName\":\"\",\"parentType\":\"poi\"}],\"city\":\"香港\",\"crossCity\":[]}";

        //JSONCompareResult result = JSONCompare.compareJSON(expected, actual, JSONCompareMode.NON_EXTENSIBLE);

        expected = "[{\"start\":1,\"count\":50,\"resultKeys\":[\"UserInfo\",\"UserExt\",\"User\",\"UserBind\"],\"conditions\":{\"userName\":[\"fyylmfy2760\"]},\"outEncrypt\":true},{\"source\":\"UNKNOWN\",\"encrypt\":{\"inEncrypt\":false,\"outEncrypt\":false},\"product\":\"QUNAR_PC_BROWSER\"}]";
        actual = "[{\"outEncrypt\":true,\"resultKeys\":[\"User\",\"UserExt\",\"UserInfo\",\"UserBind\"],\"start\":1,\"count\":50,\"conditions\":{\"userName\":[\"fyylmfy2760\"]}},{\"product\":\"QUNAR_PC_BROWSER\",\"encrypt\":{\"outEncrypt\":false,\"inEncrypt\":false},\"source\":\"UNKNOWN\"}]";

        expected = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4},\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING222\"},{\"INOVICE\":\"un-matched status: CONFIRMING\",\"AUTHORIZE\":\"un-matched status: CONFIRMING\",\"GUARANTEE\":\"non-guaranteeing status: CONFIRMING\",\"CREDIT_CARD_GUARANTEE\":\"non-guaranteeing status: CONFIRMING\",\"TO_REPAY\":\"no repay-order\",\"URGE_CONFIRM\":\"interfaceCode doesnot match: expected=hecheng, got=ctripGroup\",\"CASH_BACK\":\"non-cashback-order\",\"MODIFY_ORDER\":\"flow_switch_reason\",\"COMMENT\":\"un-matched status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING\"}],\"qstarView\":[]}";
        actual = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4},\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\"},{\"PAY\":\"status is not PAYING: CONFIRMING\",\"CASH_BACK\":\"non-cashback-order\",\"TO_REPAY\":\"no repay-order\",\"INOVICE\":\"un-matched status: CONFIRMING\",\"MODIFY_ORDER\":\"non-hecheng-order\",\"COMMENT\":\"un-matched status: CONFIRMING\",\"CREDIT_CARD_GUARANTEE\":\"non-guaranteeing status: CONFIRMING\",\"AUTHORIZE\":\"un-matched status: CONFIRMING\",\"URGE_CONFIRM\":\"interfaceCode doesnot match: expected=hecheng, got=ctripGroup\",\"GUARANTEE\":\"non-guaranteeing status: CONFIRMING\"}],\"qstarView\":[]}";

        expected = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4},\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING1\",\"PAY\":\"status is not PAYING: CONFIRMING\"},{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING1\"}],\"qstarView\":[]}";
        actual = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4},\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING2\",\"PAY\":\"status is not PAYING: CONFIRMING\"},{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING2\"}],\"qstarView\":[]}";


        expected = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":false,\"panelOrderChooser\":2,\"orderStatusInfo\":'{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4}',\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING1\",\"PAY\":\"status is not PAYING: CONFIRMING\"},{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING1\"}],\"qstarView\":[]}";
        actual = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"newVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":{\"tip\":\"您的订单已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4},\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING2\",\"PAY\":\"status is not PAYING: CONFIRMING\"},{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING2\"}],\"qstarView\":[]}";
        actual = "{\"status\":0,\"errMtns\":{\"pageto\":-1},\"oldVersion\":true,\"panelOrderChooser\":2,\"orderStatusInfo\":'{\"top\":\"您的订单ss已经提交成功，我们将尽快确认\",\"statusText\":\"等待酒店确认\",\"statusCode\":4}',\"mainOpBtns\":[{\"actId\":1,\"menu\":\"取消订单\",\"act\":2,\"msg\":\"订单可免费取消，您确定要取消订单？\"}],\"noBtnReason\":[{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING2\",\"PAY\":\"status is not PAYING: CONFIRMING\"},{\"BOOK_AGAIN\":\"un-mathced status: CONFIRMING\",\"PAY\":\"status is not PAYING: CONFIRMING2\"}],\"qstarView\":[]}";


        expected = "{\"code\":0,\"msg\":\"\", \"extra\":[],\"data\":{\"shareInfo\":\"{\\\"title\\\":\\\"分享领礼包\\\",\\\"detail\\\":\\\"分享给好友，一起领礼包吧\\\",\\\"amount\\\":\\\"600\\\",\\\"amountSign\\\":\\\"￥\\\",\\\"amountTip\\\":\\\"最高\\\",\\\"bgImgUrl\\\":\\\"https://simg1.qunarzz.com/site/images/zhuanti/huodong/giftPacketBookShare_android.png\\\",\\\"bgColor\\\":-5973,\\\"shareActionTxt\\\":\\\"立即分享\\\",\\\"cancelActionTxt\\\":\\\"给钱也不要>\\\",\\\"sharedTitle\\\":\\\"送您600元旅游大礼包，想去哪儿就去哪儿！\\\",\\\"sharedMsg\\\":\\\"去哪儿礼包限时放送，呼唤小伙伴，还有200元现金拿不停！\\\",\\\"sharedImgUrl\\\":\\\"https://simg1.qunarzz.com/site/images/wap/home/recommend/giftpk_share_icon_v11.jpg\\\",\\\"sharedUrl\\\":\\\"https://tuiguang.qunar.com/h5/red/secondversionvipred04721?bd_source=dlb_gongxiang\\\",\\\"detailFontAndroid\\\":\\\"15\\\",\\\"titleFontAndroid\\\":\\\"35\\\",\\\"detailFontIos\\\":\\\"12\\\",\\\"titleFontIos\\\":\\\"30\\\",\\\"from\\\":1,\\\"newDetail\\\":\\\"分享给好友，一起领礼包吧\\\"}\"},\"ok\":true}";
        actual = "{\"code\":0,\"msg\":\"\", \"extra\":[],\"data\":{\"shareInfo\":\"{\\\"title\\\":\\\"分享领礼包\\\",\\\"detail\\\":\\\"分享给好友，一起领礼包吧\\\",\\\"amount\\\":\\\"600\\\",\\\"amountSign\\\":\\\"￥\\\",\\\"amountTip\\\":\\\"最高\\\",\\\"bgImgUrl\\\":\\\"https://simg1.qunarzz.com/site/images/zhuanti/huodong/giftPacketBookShare_android.png\\\",\\\"bgColor\\\":-5973,\\\"shareActionTxt\\\":\\\"立即分享\\\",\\\"cancelActionTxt\\\":\\\"给钱也不要>\\\",\\\"sharedTitle\\\":\\\"送您600元旅游大礼包，想去哪儿就去哪儿！\\\",\\\"sharedMsg\\\":\\\"去哪儿礼包限时放送，呼唤小伙伴，还有200元现金拿不停！\\\",\\\"sharedImgUrl\\\":\\\"https://simg1.qunarzz.com/site/images/wap/home/recommend/giftpk_share_icon_v11.jpg\\\",\\\"sharedUrl\\\":\\\"https://tuiguang.qunar.com/h5/red/secondversionvipred54220?bd_source=dlb_gongxiang\\\",\\\"detailFontAndroid\\\":\\\"15\\\",\\\"titleFontAndroid\\\":\\\"35\\\",\\\"detailFontIos\\\":\\\"12\\\",\\\"titleFontIos\\\":\\\"30\\\",\\\"from\\\":1,\\\"newDetail\\\":\\\"分享给好友，一起领礼包吧\\\"}\"},\"ok\":true}";


        expected = "{\"status\":-1,\"des\":\"服务器累了，请稍后重试\",\"errSys\":\"离店日期不能为空\",\"errType\":\"other\",\"errTypeName\":\"其他\",\"errMtns\":{\"prompt\":\"服务器累了，请稍后重试\",\"pageto\":-1},\"action\":{\"pageto\":-1}}";
        actual = "{\"action\":{\"pageto\":-1},\"des\":\"服务器累了，请稍后重试\",\"errMtns\":{\"pageto\":-1,\"prompt\":\"服务器累了，请稍后重试\"},\"errSys\":\"离店日期不能为空\",\"errType\":\"other\",\"errTypeName\":\"其他\",\"status\":-1}";



        expected = "[\"SUBMIT_IDEMPOTENT_fgxq49njsfi1\",\"{\\\"status\\\":-1,\\\"des\\\":\\\"服务器累了aa，请稍后重试\\\",\\\"errSys\\\":\\\"离店日期不能为空\\\",\\\"errType\\\":\\\"other\\\",\\\"errTypeName\\\":\\\"其他\\\",\\\"errMtns\\\":{\\\"prompt\\\":\\\"服务器累了，请稍后重试\\\",\\\"pageto\\\":-1},\\\"action\\\":{\\\"pageto\\\":-1}}\",\"NX\",\"EX\",1800]";
        actual = "[\"SUBMIT_IDEMPOTENT_fgxq49njsfi\",\"{\\\"action\\\":{\\\"pageto\\\":-1},\\\"des\\\":\\\"服务器累了，请稍后重试\\\",\\\"errMtns\\\":{\\\"pageto\\\":-1,\\\"prompt\\\":\\\"服务器累了，请稍后重试\\\"},\\\"errSys\\\":\\\"离店日期不能为空\\\",\\\"errType\\\":\\\"other\\\",\\\"errTypeName\\\":\\\"其他\\\",\\\"status\\\":-1}\",\"NX\",\"EX\",1800]";


        expected = "[{\"userId\":\"212904433\",\"terminalInfo\":\"{\\\"uid\\\":\\\"42A4CC02-8191-49D1-8F54-F7ABBE63BF93\\\",\\\"gid\\\":\\\"EC82C905-089B-A411-7F26-8C11624DA023\\\",\\\"pid\\\":\\\"10010\\\",\\\"platformType\\\":\\\"80\\\",\\\"clientGps\\\":\\\"113.479775,34.941666\\\",\\\"ip\\\":\\\"10.95.158.132\\\"}\",\"orderAmount\":[113.0],\"source\":\"APP\",\"scene\":\"PREPOSE\",\"productId\":25623418172,\"productType\":38,\"extra\":{\"PC_PRODUCT_DETAIL\":\"{\\\"hotelPayTypeCode\\\":null,\\\"hotelOrderResource\\\":null,\\\"hotelPaymentType\\\":null,\\\"hotelCityName\\\":null,\\\"hotelId\\\":\\\"184366217\\\",\\\"hotelName\\\":null,\\\"hotelSeq\\\":\\\"handan_4505\\\",\\\"hotelProductType\\\":0,\\\"supplier_id\\\":\\\"1588566\\\",\\\"supplier_name\\\":null,\\\"hotelCoupon\\\":null,\\\"hotelCheckInDate\\\":\\\"20191018\\\",\\\"hotelCheckOutDate\\\":\\\"20191019\\\",\\\"slaveHotel\\\":{\\\"hotelAddress\\\":null,\\\"hotelCountry\\\":null,\\\"hotelLevel\\\":null,\\\"hotelProvince\\\":null},\\\"hotelCustomerNames\\\":[],\\\"hotel_Device\\\":{\\\"hotelUid\\\":\\\"42A4CC02-8191-49D1-8F54-F7ABBE63BF93\\\",\\\"hotelGid\\\":\\\"EC82C905-089B-A411-7F26-8C11624DA023\\\",\\\"hotelVid\\\":\\\"80011196\\\",\\\"hotelPid\\\":\\\"10010\\\",\\\"hotelCookie\\\":null},\\\"hotel_Client\\\":{\\\"hotelRoom_name\\\":null,\\\"hotelRoom_amount\\\":null,\\\"hotelArrival_time\\\":null,\\\"hotel_UserIp\\\":\\\"10.95.158.132\\\",\\\"hotelCreate_date\\\":\\\"20191018173003\\\",\\\"hotelBooking_channel\\\":null},\\\"hotel_Agent\\\":{\\\"hotelReceiver\\\":null,\\\"hotelSupplier_id\\\":\\\"1588566\\\",\\\"hotelInvoice_title\\\":null,\\\"hotelReceiver_addr\\\":null,\\\"hotelReceiver_phone\\\":null},\\\"hotel_Invoice\\\":null,\\\"originalOrderAmount\\\":null,\\\"hotelOrderType\\\":null}\"}}]";

        actual = "[{\"orderAmount\":[113.0],\"productId\":25623418172,\"extra\":{\"PC_PRODUCT_DETAIL\":\"{\\\"hotelPayTypeCode\\\":null,\\\"hotelOrderResource\\\":null,\\\"hotelPaymentType\\\":null,\\\"hotelCityName\\\":null,\\\"hotelId\\\":\\\"184366217\\\",\\\"hotelName\\\":null,\\\"hotelSeq\\\":\\\"handan_4505\\\",\\\"hotelProductType\\\":0,\\\"supplier_id\\\":\\\"1588566\\\",\\\"supplier_name\\\":null,\\\"hotelCoupon\\\":null,\\\"hotelCheckInDate\\\":\\\"20191018\\\",\\\"hotelCheckOutDate\\\":\\\"20191019\\\",\\\"slaveHotel\\\":{\\\"hotelAddress\\\":null,\\\"hotelCountry\\\":null,\\\"hotelLevel\\\":null,\\\"hotelProvince\\\":null},\\\"hotelCustomerNames\\\":[],\\\"hotel_Device\\\":{\\\"hotelUid\\\":\\\"42A4CC02-8191-49D1-8F54-F7ABBE63BF93\\\",\\\"hotelGid\\\":\\\"EC82C905-089B-A411-7F26-8C11624DA023\\\",\\\"hotelVid\\\":\\\"80011196\\\",\\\"hotelPid\\\":\\\"10010\\\",\\\"hotelCookie\\\":null},\\\"hotel_Client\\\":{\\\"hotelRoom_name\\\":null,\\\"hotelRoom_amount\\\":null,\\\"hotelArrival_time\\\":null,\\\"hotel_UserIp\\\":\\\"10.95.158.132\\\",\\\"hotelCreate_date\\\":\\\"20191018173004\\\",\\\"hotelBooking_channel\\\":null},\\\"hotel_Agent\\\":{\\\"hotelReceiver\\\":null,\\\"hotelSupplier_id\\\":\\\"1588566\\\",\\\"hotelInvoice_title\\\":null,\\\"hotelReceiver_addr\\\":null,\\\"hotelReceiver_phone\\\":null},\\\"hotel_Invoice\\\":null,\\\"originalOrderAmount\\\":null,\\\"hotelOrderType\\\":null}\"},\"source\":\"APP\",\"userId\":\"212904433\",\"terminalInfo\":\"{\\\"uid\\\":\\\"42A4CC02-8191-49D1-8F54-F7ABBE63BF93\\\",\\\"gid\\\":\\\"EC82C905-089B-A411-7F26-8C11624DA023\\\",\\\"pid\\\":\\\"10010\\\",\\\"platformType\\\":\\\"80\\\",\\\"clientGps\\\":\\\"113.479775,34.941666\\\",\\\"ip\\\":\\\"10.95.158.132\\\"}\",\"productType\":38,\"scene\":\"PREPOSE\"}]";


        //expected = "[{\"messageId\":\"191023.040410.10.88.208.234.20857.6011\",\"subject\":\"hotel.qta.order.core.sendsms.subject\",\"durable\":true,\"storeAtFailed\":false,\"tags\":[],\"attrs\":{\"qmq_expireTime\":1571861050251,\"qmq_appCode\":\"h_qta_parent_order\",\"qmq_env\":\"prod\",\"hotel.qta.order.core.sendsms.key\":\"{\\\"appId\\\":null,\\\"orderNo\\\":102062889270,\\\"command\\\":\\\"USER_CREDIT_ORDER_DEDUCT_SUCCESS\\\",\\\"phone\\\":\\\"186q6w65599\\\",\\\"emailAddress\\\":null,\\\"forbidFilter\\\":false,\\\"param\\\":null,\\\"resendOrder\\\":false,\\\"userSms\\\":true}\",\"qmq_createTIme\":1571774650251,\"qmq_traceContext\":\"{\\\"M_C\\\":\\\"T\\\",\\\"ROOT_SPAN_ID\\\":\\\"1.37.1.1.7.1.3.1.6.1.8.1.43.2.2.12.1.3.1.6.2.1.1.5.2.1.1.10.2.1.1.1.2.1.1.2.1.4.1.8.1.43.2.1\\\"}\",\"qmq_subEnv\":\"parent\",\"qmq_reliabilityLevel\":\"High\",\"qmq_traceId\":\"h_supplier_orderAdapter_191023.040400.10.90.59.144.17307.2623687_0\",\"ORDER_ID\":102062889270,\"qmq_spanId\":\"1.37.1.1.7.1.3.1.6.1.8.1.43.2.2.12.1.3.1.6.2.1.1.5.2.1.1.10.2.1.1.1.2.1.1.2.1.4.1.8.1.43.2.1.8.3\",\"VERSION\":42,\"COMMAND\":\"USER_CREDIT_ORDER_DEDUCT_SUCCESS\"},\"maxRetryNum\":-1,\"newqmq\":false,\"bigMessage\":false}]";
        //actual = "[{\"durable\":true,\"storeAtFailed\":false,\"subject\":\"hotel.qta.order.core.sendsms.subject\",\"messageId\":\"191023.171304.10.93.94.209.6240.0\",\"newqmq\":false,\"maxRetryNum\":-1,\"bigMessage\":false,\"tags\":[],\"attrs\":{\"qmq_expireTime\":1571908384215,\"ORDER_ID\":102062889270,\"qmq_appCode\":\"h_qta_parent_order\",\"qmq_env\":\"beta\",\"hotel.qta.order.core.sendsms.key\":\"{\\\"appId\\\":null,\\\"orderNo\\\":102062889270,\\\"command\\\":\\\"USER_CREDIT_ORDER_DEDUCT_SUCCESS\\\",\\\"phone\\\":\\\"186q6w65599\\\",\\\"emailAddress\\\":null,\\\"forbidFilter\\\":false,\\\"param\\\":null,\\\"resendOrder\\\":false,\\\"userSms\\\":true}\",\"qmq_createTIme\":1571821984215,\"VERSION\":42,\"qmq_subEnv\":\"n3_37639\",\"COMMAND\":\"USER_CREDIT_ORDER_DEDUCT_SUCCESS\"}}]";


        List<String> ignorePathList = Arrays.asList("newVersion", "orderStatusInfo.$.top");

        JSONCompareConfig compareConfig = new JSONCompareConfig();
        compareConfig.setIgnorePathList(ignorePathList);

        JSONComparator jsonCompare = new ComplexComparator(JSONCompareMode.STRICT, compareConfig, true);
        JSONCompareResult result = JSONCompare.compareJSON(expected, actual, jsonCompare);
        //JSONCompareResult result = JSONCompare.compareJSON(Files.readFirstLine(new File("/Users/zippoy/workspace/case-server/case-common/src/test/java/expected"), UTF_8), Files.readFirstLine(new File("/Users/zippoy/workspace/case-server/case-common/src/test/java/actual"), UTF_8), jsonCompare);

        System.out.println(result);

        System.out.println("-----------------");

        String onlineArg = "[{\"start\":1,\"count\":50,\"resultKeys\":[\"UserInfo\",\"User\",\"UserExt\",\"UserBind\"],\"conditions\":{\"userName\":[\"eripoes0028\"]},\"outEncrypt\":true},{\"source\":\"UNKNOWN\",\"encrypt\":{\"inEncrypt\":false,\"outEncrypt\":false},\"product\":\"QUNAR_PC_BROWSER\",\"userSource\":\"www\"}]";
        String betaArg = "[{\"outEncrypt\":true,\"resultKeys\":[\"User\",\"UserBind\",\"UserExt\",\"UserInfo\"],\"start\":1,\"count\":50,\"conditions\":{\"userName\":[\"eripoes0028\"]}},{\"product\":\"QUNAR_PC_BROWSER\",\"encrypt\":{\"outEncrypt\":false,\"inEncrypt\":false},\"userSource\":\"www\",\"source\":\"UNKNOWN\"}]";

    }


}
